title: Jasons Talks
baseurl: https://jsntn.github.io/talks
url: https://jsntn.github.io/talks
author: Jason
email: hi@jsntn.com
description: > # this means to ignore newlines until "baseurl:"
  The talks from Jason...

# build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /:title.html

# PODCAST
license: CC-BY-SA
podcast:
  title: Jasons Talks
  subtitle: A seeker lives in the past
  url: /podcast.xml
  albumCover: /images/jt.jpeg
  summary: >
    Just some talks from Jason...<br />
    <a href="https://jsntn.github.io/talks">jsntn.github.io/talks</a>