title: Jasons Talks
baseurl: https://jsntn.github.io/talks
author: Jason
email: hi@jsntn.com
description: > # this means to ignore newlines until "baseurl:"
  The talks from Jason...

# build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /:title.html
